trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)  # Reference the pipeline variable here

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    # Use the GITHUB_TOKEN variable in your script
    ng build --prod --token $(GITHUB_TOKEN)
  displayName: 'npm install and build'


